# Generated by Django 6.1 on 2026-08-17 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('EXCHANGE_REQUEST', 'New exchange request'), ('EXCHANGE_ACCEPTED', 'Exchange accepted'), ('EXCHANGE_REJECTED', 'Exchange rejected'), ('DONATION_REQUEST', 'New donation request'), ('DONATION_ACCEPTED', 'Donation accepted'), ('ORDER', 'Order update'), ('MESSAGE', 'New message'), ('PRODUCT_SOLD', 'Product sold'), ('REVIEW', 'Review received'), ('REPAIR', 'Repair update'), ('GENERAL', 'General')], default='GENERAL', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
