# Generated by Django 6.1 on 2026-08-17 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactCategoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_weight_saved_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('avg_co2_saved_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact_config', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ImpactRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('SALE', 'Sale'), ('DONATION', 'Donation'), ('EXCHANGE', 'Exchange')], max_length=20)),
                ('estimated_weight_saved', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estimated_co2_saved', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impact_records', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
